### ISSUE TITLE
lin--buffer-hidden-p: Wrong type argument: sequencep, #<buffer *scratch*>

### ISSUE THREAD

**Issue by fintelkai** [protesilaos/lin#1]
Hi Prot, the current version fails on my system. I've tried it with `emacs -Q` and just loading `lin.el`. When I then do `M-x lin-global-mode`, I get this error: `lin--buffer-hidden-p: Wrong type argument: sequencep, #<buffer *scratch*>`. It doesn't matter what buffer I'm in, so if I'm in a daily notes file, I get `lin--buffer-hidden-p: Wrong type argument: sequencep, #<buffer 2024-09-05.org>`.

**Comment by protesilaos** [comment]
Oops, my mistake! I just updated it. Thank you for letting me know!
